
PAIRS={
    'IC MARKETS:41' : 'ICMARKETS_XAU-USD',
    'IC MARKETS:10026' : 'ICMARKETS_BTC-USD',
    'OANDA:XAU_USD' : 'OANDA_XAU-USD',
    'FXCM:XAU/USD': 'FXCM_XAU-USD',
    'FXCM:BTC/USD': 'FXCM_BTC-USD',
    'BINANCE:BTCUSDT': 'BINANCE_BTC-USDT',
    'KUCOIN:BTC-USDT': 'KUCOIN_BTC-USDT',
    'BINANCE:ETHUSDT': 'BINANCE_ETH-USDT',
    'KUCOIN:ETH-USDT': 'KUCOIN_ETH-USDT',
}