version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    restart: unless-stopped

  kafka1:
    image: wurstmeister/kafka:latest
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    restart: unless-stopped

  kafka2:
    image: wurstmeister/kafka:latest
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    restart: unless-stopped

  producer1:
    build: ./app
    container_name: producer1
    command: python /app/test-producer1.py
    volumes:
      - ./app:/app
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - kafka2


  producer2:
    build: ./app
    container_name: producer2
    command: python /app/test-producer2.py
    volumes:
      - ./app:/app
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - kafka2

  consumer:
    build: ./app
    container_name: consumer
    command: python /app/test-consumer.py
    volumes:
      - ./app:/app
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - kafka2

networks:
  kafka-net:
    driver: bridge